---
development:
  cloud_name: rociac
  api_key: '396632457319185'
  api_secret: IsXnyVTo6o-ZXjzJcrOVoI7lH7s
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: rociac
  api_key: '396632457319185'
  api_secret: IsXnyVTo6o-ZXjzJcrOVoI7lH7s
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: rociac
  api_key: '396632457319185'
  api_secret: IsXnyVTo6o-ZXjzJcrOVoI7lH7s
  enhance_image_tag: true
  static_file_support: false
